APT::FTPArchive::Release {
    Origin "MKstar From Switch";
    Label "MKstar's Misc Repo";
    Suite "stable";
    Codename "stable";
    Architectures "amd64";
    Components "main";
    Description "My APT repo for misc stuff";
};
